name: PatchTST

params:
  seq_len: ${dataset.seq_len}
  c_in: 1
  c_out: 1
  pred_dim: 1
  n_layers: 2
  n_heads: 4
  d_model: 256
  d_ff: 1024
  dropout: 0.09
  attn_dropout: 0.09
  patch_len: 8
  stride: 6
  padding_patch: True
  revin: True
  affine: False
  individual: False
  subtract_last: False
  decomposition: False
  kernel_size: 25
  activation: 'gelu'
  norm: 'BatchNorm'
  pre_norm: False
  res_attention: True
  store_attn: False

hyperparameters_vary:
  pred_dim:
    optuna_type: const
    value: 1
  c_in:
    optuna_type: const
    value: 1
  c_out:
    optuna_type: const
    value: 1
  seq_len:
    optuna_type: const
    value: ${dataset.seq_len}
  dropout:
    optuna_type: float
    low: 0.1
    high: 0.7
    step: 0.1

attack_train_mode: False
