name: S4

params:
  input_dim: 1
  hidden_dim: 64
  output_dim: 1
  dropout: 0.5

hyperparameters_vary:
  dropout:
    optuna_type: float
    low: 0.1
    high: 0.7
    step: 0.1

attack_train_mode: False
