#! /bin/bash

DOCKER_NAME="adversarial_attacks" # username in container
CONTAINER_NAME=$USER"-hid_aa" # name of container
SRC="ТУТ ПУТЬ К ТВОИМ ДАННЫМ" # source directory (supposedly, this repo's path is /home/${USER}/${SRC})

# to get these values type "id" in shell termilal
DOCKER_USER_ID=$(id -u) 
DOCKER_GROUP_ID=$(id -g)
