#! /bin/bash
source credentials

docker run \
 -d \
 -p ${CONTAINER_PORT}:8890 \
 --shm-size=8g \
 --memory=60g \
 --cpus=16 \
 --user ${DOCKER_USER_ID}:${DOCKER_GROUP_ID} \
 --name ${CONTAINER_NAME} \
 --rm -it --init \
 -v ${HOME}/${SRC}:/app \
 --runtime=nvidia \
 ${DOCKER_NAME} bash

 #--gpus all
