#! /bin/bash
source credentials

docker run \
  -d \
  --shm-size=8g \
  --memory=120g \
  --cpus=16 \
  --user ${DOCKER_USER_ID}:${DOCKER_GROUP_ID} \
  --name ${CONTAINER_NAME} \
  --rm -it --init \
  --gpus '"device=0,2"' \
  -v /home/${USER}/${SRC}:/app \
  ${DOCKER_NAME} bash
