name: TrainAttack
short_name: train_attack
named_params: [eps]
is_trainable: True

attack_params:
  train_eps: 1
  eps: ${.train_eps}
  n_steps: 1
  is_clamp: False
  disc_alpha: 0.0
  use_sigmoid: True

# Optional discriminator regularization
list_reg_model_params: []

batch_size: 64

training_params:
# best
  alpha_l2: 0.001
  criterion_name: BCELoss
  criterion_params: None
  early_stop_patience: 100
  n_epochs: 5
  optimizer_name: Adam
  optimizer_params:
    lr: 0.0001 # default: 0.001
  print_every: 1
  scheduler_name: StepLR
  scheduler_params:
    gamma: 0.8
    step_size: 30
  train_self_supervised: false

  # criterion_name: BCELoss
  # criterion_params: None
  # optimizer_name: Adam
  # optimizer_params:
  #   lr: 0.001
  # scheduler_name: StepLR
  # scheduler_params:
  #   step_size: 30
  #   gamma: 0.8
  # n_epochs: 5
  # alpha_l2: 0.001
  # early_stop_patience: 100
  # print_every: 1
  # train_self_supervised: False



hyperparameters_vary:
  train_eps:
    optuna_type: choice
    choices: [1]
  
  eps:
    optuna_type: choice
    choices: [1]  

  n_steps:
    optuna_type: choice
    choices: [1]
  n_epochs:
    optuna_type: const
    value: 10

  patch_len:
    optuna_type: choice
    choices: [16, 32, 64, 128]

  stride:
    optuna_type: choice
    choices: [4, 8, 16, 32]

  lr:
    optuna_type: choice
    choices: [0.001, 0.01, 0.0001]

  dropout:
    optuna_type: choice
    choices: [0.1, 0.3, 0.6]
  attn_dropout:
    optuna_type: float
    low: 0.0
    high: 0.3
    step: 0.05

  n_layers:
    optuna_type: choice
    choices: [1, 2, 3, 4]

  d_model:
    optuna_type: choice
    choices: [128, 256, 512]

  d_ff:
    optuna_type: choice
    choices: [512, 1024, 2048]

  n_heads:
    optuna_type: choice
    choices: [4, 8]

  revin:
    optuna_type: choice
    choices: [true, false]

  norm:
    optuna_type: choice
    choices: [BatchNorm, LayerNorm]


  # eps:
  #   optuna_type: float
  #   low: 0.8
  #   high: 1
  #   log: True
  # train_eps:
  #   optuna_type: float
  #   low: 0.1
  #   high: 1
  #   log: True