#! /bin/bash

DOCKER_NAME="adversarial_attacks"
CONTAINER_NAME="sokerin-AA"
SRC="AA/Hidden_adversarial_attacks"
DOCKER_USER_ID=1033 # to get these values type "id" in shell termilal
DOCKER_GROUP_ID=1034
CONTAINER_PORT=8893 # used in launch_container file