name: FGSMAttackHarmonicLoss
short_name: fgsm_harmonic_attack
named_params: [eps, n_steps]

attack_params:
  eps: 0.03
  n_steps: 50
  # alpha: 0.01
  use_sigmoid: False

list_reg_model_params:
  - model_${attack_model.name}_${model_id_attack}_${dataset.name}_attack_fgsm_attack__eps=0.03__n_steps=10



# list_reg_model_params:
#   - model_id : 100
#     model_name: fgsm_attack_eps=0.03_nsteps=10


hyperparameters_vary:
  eps:
    optuna_type: const
    value: 0.03
  n_steps:
    optuna_type: const
    value: 50