name: MBAPatchTSTAttack
short_name: mba_patchtst_attack
named_params: [eps, n_steps]

attack_params:
  eps: 0.5
  n_steps: 1
  clamp: null

attacker_model_params:
  name: AttackPatchTST
  params:
    hidden_dim: 128
    x_dim: 1
    activation_type: "tanh"
  patch_kwargs:
    seq_len: 144
    n_layers: 3
    n_heads: 8
    d_model: 512
    d_ff: 2048
    dropout: 0.4
    patch_len: 28
    stride: 24
    revin: true
    res_attention: true
  path: "checkpoints/attackers/attacker_AttackPatchTST_100_PowerCons.pth"

