name: PGDAttack
short_name: pgd_attack
named_params: [eps, n_steps, eta]

attack_params:
  eps: 0.03
  n_steps: 50
  eta: 1
  norm: null

hyperparameters_vary:
  eps:
    optuna_type: float
    low: 0.01
    high: 0.5
    log: True
  n_steps:
    optuna_type: const
    value: 50