name: AttackPatchTST
short_name: attack_patchtst

model_params:
  hidden_dim: 128
  x_dim: 1
  activation_type: "tanh"
  patch_kwargs:
    seq_len: 144
    n_layers: 3
    n_heads: 8
    d_model: 512
    d_ff: 2048
    dropout: 0.4
    attn_dropout: 0.0
    patch_len: 28
    stride: 24
    padding_patch: true
    revin: true
    affine: false
    individual: false
    subtract_last: false
    decomposition: false
    kernel_size: 25
    activation: "gelu"
    norm: "BatchNorm"
    pre_norm: false
    res_attention: true
    store_attn: false

hyperparameters_vary:
  hidden_dim:
    optuna_type: categorical
    choices: [64, 128, 256, 512]
  activation_type:
    optuna_type: categorical
    choices: ["identity", "tanh", "relu"]
  patch_kwargs:
    n_layers:
      optuna_type: int
      low: 1
      high: 4
    d_model:
      optuna_type: categorical
      choices: [256, 512, 768]
    dropout:
      optuna_type: float
      low: 0.1
      high: 0.6
      step: 0.1
    patch_len:
      optuna_type: int
      low: 8
      high: 48
      step: 4
    stride:
      optuna_type: int
      low: 4
      high: 24
      step: 4
